function t396_init(recid){var data='';var resolution=t396_detectResolution();var allRecords=document.getElementById('allrecords');var record=document.getElementById('rec'+recid);var zeroBlock=record?record.querySelector('.t396'):null;var artBoard=record?record.querySelector('.t396__artboard'):null;window.tn_window_width=document.documentElement.clientWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;t396_initTNobj();t396_switchResolution(resolution);t396_updateTNobj();t396_artboard_build(data,recid);var isTouchDevice='ontouchend' in document;window.addEventListener('resize',function(){tn_console('>>>> t396: Window on Resize event >>>>');t396_waitForFinalEvent(function(){if(window.isMobile||isTouchDevice){if(document.documentElement.clientWidth!==window.tn_window_width){t396_doResize(recid)}}else{t396_doResize(recid)}},500,'resizeruniqueid'+recid)});window.addEventListener('orientationchange',function(){tn_console('>>>> t396: Orient change event >>>>');t396_waitForFinalEvent(function(){t396_doResize(recid)},600,'orientationuniqueid'+recid)});window.addEventListener('load',function(){t396_allelems__renderView(artBoard);var blockOverflow=artBoard?window.getComputedStyle(artBoard).getPropertyValue('overflow'):'';if(typeof t_lazyload_update==='function'&&blockOverflow==='auto'&&artBoard){artBoard.addEventListener('scroll',t_throttle(function(){var dataLazy=allRecords?allRecords.getAttribute('data-tilda-lazy'):null;if(window.lazy==='y'||dataLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}},500))}
if(window.location.hash!==''&&blockOverflow==='visible'){if(artBoard)artBoard.style.overflow='hidden';setTimeout(function(){if(artBoard)artBoard.style.overflow='visible'},1)}});if(record&&zeroBlock&&artBoard&&record.getAttribute('data-connect-with-tab')==='yes'){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)});$(zeroBlock).bind('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)})}
setTimeout(function(){if(record&&record.closest('#allrecordstable')&&zeroBlock&&artBoard){zeroBlock.addEventListener('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)});$(zeroBlock).bind('displayChanged',function(){t396_allelems__renderView(artBoard);t396_doResize(recid)})}},1000);if(window.isSafari&&zeroBlock){zeroBlock.classList.add('t396_safari')}
var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':null;if(isScaled&&!isTildaModeEdit)t396_scaleBlock(recid)}
function t396_isOnlyScalableBrowser(){var isFirefox=navigator.userAgent.search('Firefox')!==-1;var isOpera=(!!window.opr&&!!window.opr.addons)||!!window.opera||navigator.userAgent.indexOf(' OPR/')!==-1;return isFirefox||isOpera}
function t396_scaleBlock(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var resolution=t396_detectResolution();var record=document.getElementById('rec'+recid);var zeroBlockElements=record?record.querySelectorAll('.t396__elem'):[];var artBoard=record?record.querySelector('.t396__artboard'):null;if(artBoard){var artBoardWidth=artBoard.clientWidth;var updatedBlockHeight=Math.floor(artBoard.clientHeight*window.tn_scale_factor);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;if(artBoardHeightVH){var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var scaledMinHeight=artBoardMinHeight*window.tn_scale_factor;updatedBlockHeight=(scaledMinHeight>=artBoardMaxHeight)?scaledMinHeight:artBoardMaxHeight}
artBoard.classList.add('t396__artboard_scale');var styleStr='<style class="t396__scale-style">'+'.t-rec#rec'+recid+' { overflow: visible; }'+'#rec'+recid+' .t396__carrier,'+'#rec'+recid+' .t396__filter,'+'#rec'+recid+' .t396__artboard {'+'height: '+updatedBlockHeight+'px !important;'+'width: 100vw !important;'+'max-width: 100%;'+'}'+'</style>';artBoard.insertAdjacentHTML('beforeend',styleStr)}
Array.prototype.forEach.call(zeroBlockElements,function(zeroBlockElement){var atom=zeroBlockElement.querySelector('.tn-atom');var containerProp=t396_elem__getFieldValue(zeroBlockElement,'container');if(containerProp==='grid'){if(isOnlyScalable){if(atom){var atomParent=atom.parentNode;var div=document.createElement('div');div.classList.add('tn-atom__scale-wrapper');div.style.transform='scale('+window.tn_scale_factor+')';if(atomParent)atomParent.removeChild(atom);div.appendChild(atom);if(atomParent)atomParent.appendChild(div)}}else{zeroBlockElement.style.zoom=window.tn_scale_factor;if(zeroBlockElement.getAttribute('data-elem-type')==='text'&&resolution<1200&&atom){atom.style.webkitTextSizeAdjust='auto'}
if(atom)atom.style.transformOrigin='center'}}})}
function t396_doResize(recid){var isOnlyScalable=t396_isOnlyScalableBrowser();var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var resolution=t396_detectResolution();var scaleStyle=record?record.querySelector('.t396__scale-style'):null;t396_removeElementFromDOM(scaleStyle);if(!isOnlyScalable){var elements=record?record.querySelectorAll('.t396__elem'):[];Array.prototype.forEach.call(elements,function(element){element.style.zoom='';var atom=element.querySelector('.tn-atom');if(atom)atom.style.transformOrigin=''})}else{var atoms=record?record.querySelectorAll('.tn-atom'):[];Array.prototype.forEach.call(atoms,function(atom){var atomWrapper=atom.closest('.tn-atom__scale-wrapper');var atomParent=atomWrapper?atomWrapper.parentNode:null;if(atomParent)atomParent.removeChild(atomWrapper);if(atomParent)atomParent.appendChild(atom)})}
var artBoard=record?record.querySelector('.t396__artboard'):null;var artBoardWidth=artBoard?artBoard.clientWidth:0;window.tn_window_width=window.isMobile?document.documentElement.clientWidth:window.innerWidth;window.tn_scale_factor=Math.round((window.tn_window_width/resolution)*100)/100;window.tn_scale_offset=(artBoardWidth*window.tn_scale_factor-artBoardWidth)/2;t396_switchResolution(resolution);t396_updateTNobj();t396_ab__renderView(artBoard);t396_allelems__renderView(artBoard);var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';if(isScaled&&tildaMode!=='edit')t396_scaleBlock(recid)}
function t396_detectResolution(){var windowWidth=window.isMobile?document.documentElement.clientWidth:window.innerWidth;var resolution=1200;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length-1;i++){if(windowWidth<breakpoints[i]){resolution=breakpoints[i+1]}}
return resolution}
function t396_initTNobj(){tn_console('func: initTNobj');window.tn={};window.tn.canvas_min_sizes=['320','480','640','960','1200'];window.tn.canvas_max_sizes=['480','640','960','1200',''];window.tn.ab_fields=['height','width','bgcolor','bgimg','bgattachment','bgposition','filteropacity','filtercolor','filteropacity2','filtercolor2','height_vh','valign']}
function t396_updateTNobj(){tn_console('func: updateTNobj');var allRecords=document.getElementById('allrecords');var allRecPaddingLeft=allRecords?window.getComputedStyle(allRecords).paddingLeft||'0':'0';allRecPaddingLeft=parseInt(allRecPaddingLeft,10);var allRecPaddingRight=allRecords?window.getComputedStyle(allRecords).paddingRight||'0':'0';allRecPaddingRight=parseInt(allRecPaddingRight,10);if(window.zero_window_width_hook&&window.zero_window_width_hook==='allrecords'&&allRecords){window.tn.window_width=allRecords.clientWidth-(allRecPaddingLeft+allRecPaddingRight)}else{window.tn.window_width=document.documentElement.clientWidth}
window.tn.window_height=document.documentElement.clientHeight;window.tn.curResolution;var breakpoints=[1200,960,640,480,320];for(var i=0;i<breakpoints.length;i++){if(+window.tn.curResolution===breakpoints[i]){window.tn.canvas_min_width=breakpoints[i];window.tn.canvas_max_width=i===0?window.tn.window_width:breakpoints[i-1]}}
window.tn.grid_width=window.tn.canvas_min_width;window.tn.grid_offset_left=(window.tn.window_width-window.tn.grid_width)/2}
var t396_waitForFinalEvent=(function(){var timers={};return function(callback,ms,uniqueId){if(!uniqueId){uniqueId='Don\'t call this twice without a uniqueId'}
if(timers[uniqueId]){clearTimeout(timers[uniqueId])}
timers[uniqueId]=setTimeout(callback,ms)}})();function t396_switchResolution(resolution,resolutionMax){tn_console('func: switchResolution');if(typeof resolutionMax==='undefined'){var breakpoints=[1200,960,640,480,320];breakpoints.forEach(function(breakpoint,i){if(+resolution===breakpoint){resolutionMax=i===0?'':breakpoints[i-1]}})}
window.tn.curResolution=resolution;window.tn.curResolution_max=resolutionMax}
function t396_artboard_build(data,recid){tn_console('func: t396_artboard_build. Recid:'+recid);tn_console(data);var record=document.getElementById('rec'+recid);var allRecords=document.getElementById('allrecords');var artBoard=record?record.querySelector('.t396__artboard'):null;if(!artBoard)return!1;t396_ab__renderView(artBoard);var elements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(elements,function(element){var dataType=element.getAttribute('data-elem-type');switch(dataType){case 'text':t396_addText(artBoard,element);break;case 'image':t396_addImage(artBoard,element);break;case 'shape':t396_addShape(artBoard,element);break;case 'button':t396_addButton(artBoard,element);break;case 'video':t396_addVideo(artBoard,element);break;case 'html':t396_addHtml(artBoard,element);break;case 'tooltip':t396_addTooltip(artBoard,element);break;case 'form':t396_addForm(artBoard,element);break;case 'gallery':t396_addGallery(artBoard,element);break}});artBoard.classList.remove('rendering');artBoard.classList.add('rendered');var artBoardOverflow=artBoard.getAttribute('data-artboard-ovrflw');if((artBoardOverflow==='visible'||artBoardOverflow==='visibleX')&&allRecords){allRecords.style.overflow='hidden'}
if(artBoardOverflow==='auto'){var diff=Math.abs(artBoard.offsetHeight-artBoard.clientHeight);if(diff!==0){artBoard.style.paddingBottom=diff+'px'}}
if(window.isMobile){var style=document.createElement('style');style.textContent='@media only screen and (min-width:1366px) and (orientation:landscape) and (-webkit-min-device-pixel-ratio:2) {.t396__carrier {background-attachment:scroll!important;}}';record.insertAdjacentElement('beforeend',style)}}
function t396_ab__renderView(artBoard){if(!artBoard)return!1;var fields=window.tn.ab_fields;var allRecords=document.getElementById('allrecords');var artBoardHeightVH;for(var i=0;i<fields.length;i++){t396_ab__renderViewOneField(artBoard,fields[i])}
var artBoardMinHeight=t396_ab__getFieldValue(artBoard,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoard);var isTildaModeEdit=allRecords?allRecords.getAttribute('data-tilda-mode')==='edit':!1;var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
var offsetTop;if(artBoardMinHeight===artBoardMaxHeight||(scaledMinHeight&&scaledMinHeight>=artBoardMaxHeight)){offsetTop=0}else{var artBoardVerticalAlign=t396_ab__getFieldValue(artBoard,'valign');switch(artBoardVerticalAlign){case 'top':offsetTop=0;break;case 'center':if(scaledMinHeight){offsetTop=parseFloat(((artBoardMaxHeight-scaledMinHeight)/2).toFixed(1))}else{offsetTop=parseFloat(((artBoardMaxHeight-artBoardMinHeight)/2).toFixed(1))}
break;case 'bottom':if(scaledMinHeight){offsetTop=parseFloat((artBoardMaxHeight-scaledMinHeight).toFixed(1))}else{offsetTop=parseFloat((artBoardMaxHeight-artBoardMinHeight).toFixed(1))}
break;case 'stretch':offsetTop=0;artBoardMinHeight=artBoardMaxHeight;break;default:offsetTop=0;break}}
artBoard.setAttribute('data-artboard-proxy-min-offset-top',offsetTop);artBoard.setAttribute('data-artboard-proxy-min-height',artBoardMinHeight);artBoard.setAttribute('data-artboard-proxy-max-height',artBoardMaxHeight);var filter=artBoard.querySelector('.t396__filter');var carrier=artBoard.querySelector('.t396__carrier');artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');artBoardHeightVH=parseFloat(artBoardHeightVH);if(window.isMobile&&artBoardHeightVH){var height=document.documentElement.clientHeight*artBoardHeightVH/100;artBoard.style.height=height+'px';if(filter)filter.style.height=height+'px';if(carrier)carrier.style.height=height+'px'}}
function t396_addText(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addText');var fieldsString='top,left,width,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addImage(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addImage');var fieldsString='img,width,filewidth,fileheight,top,left,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var images=element.querySelectorAll('img');Array.prototype.forEach.call(images,function(img){img.addEventListener('load',function(){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}});if(img.complete){t396_elem__renderViewOneField(element,'top');if(img.src){setTimeout(function(){t396_elem__renderViewOneField(element,'top')},2000)}}
img.addEventListener('tuwidget_done',function(){t396_elem__renderViewOneField(element,'top')})})}
function t396_addShape(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addShape');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addButton(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addButton');var fieldsString='top,left,width,height,container,axisx,axisy,caption,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);return(element)}
function t396_addVideo(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addVideo');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var videoEl=element.querySelector('.tn-atom__videoiframe');var atom=element.querySelector('.tn-atom');if(atom)atom.style.backgroundColor='#000';var videoCover=atom?atom.getAttribute('data-atom-video-has-cover'):'';if(!videoCover)videoCover='';if(videoCover==='y'&&atom){atom.addEventListener('click',function(){var iframe=videoEl?videoEl.querySelector('iframe'):null;var dataOriginal=iframe?iframe.getAttribute('data-original'):'';if(iframe)iframe.setAttribute('src',dataOriginal);atom.style.backgroundImage='none';var playBtn=atom.querySelector('.tn-atom__video-play-link');if(playBtn)playBtn.style.display='none'})}
var allRecords=document.getElementById('allrecords');var autoplay=t396_elem__getFieldValue(element,'autoplay');var showinfo=t396_elem__getFieldValue(element,'showinfo');var loop=t396_elem__getFieldValue(element,'loop');var mute=t396_elem__getFieldValue(element,'mute');var startSec=t396_elem__getFieldValue(element,'startsec');var endSec=t396_elem__getFieldValue(element,'endsec');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var url='';var script=document.createElement('script');script.textContent='lazyload_iframe = new LazyLoad({elements_selector: ".t-iframe"});';var youtubeID=videoEl?videoEl.getAttribute('data-youtubeid'):'';if(youtubeID){url='//youtube.com/embed/';url+=youtubeID+'?rel=0&fmt=18&html5=1';url+='&showinfo='+(showinfo==='y'?'1':'0');if(loop==='y'){url+='&loop=1&playlist='+youtubeID}
if(startSec>0){url+='&start='+startSec}
if(endSec>0){url+='&end='+endSec}
if(mute==='y'){url+='&mute=1'}
if(videoCover==='y'){url+='&autoplay=1';var instFlag='y';var iframeClass='';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){instFlag='lazy';iframeClass=' class="t-iframe"'}
videoEl.innerHTML='<iframe id="youtubeiframe"'+iframeClass+' width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="'+instFlag+'"></iframe>';if(autoplay==='y'&&mute==='y'&&window.lazy==='y'){element.insertAdjacentElement('beforeend',script)}
if(autoplay==='y'&&mute==='y'){atom.click()}}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe id="youtubeiframe" class="t-iframe" width="100%" height="100%" data-original="'+url+'" frameborder="0" allowfullscreen data-flag-inst="lazy"></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe id="youtubeiframe" width="100%" height="100%" src="'+url+'" frameborder="0" allowfullscreen data-flag-inst="y"></iframe>'}}}
var vimeoID=videoEl?videoEl.getAttribute('data-vimeoid'):'';if(vimeoID){url='//player.vimeo.com/video/';url+=vimeoID+'?color=ffffff&badge=0';if(showinfo==='y'){url+='&title=1&byline=1&portrait=1'}else{url+='&title=0&byline=0&portrait=0'}
if(loop==='y'){url+='&loop=1'}
if(mute==='y'){url+='&muted=1'}
if(videoCover==='y'){url+='&autoplay=1';videoEl.innerHTML='<iframe data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}else{if(tildaMode!=='edit'&&autoplay==='y'){url+='&autoplay=1'}
if(window.lazy==='y'){videoEl.innerHTML='<iframe class="t-iframe" data-original="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>';element.insertAdjacentElement('beforeend',script)}else{videoEl.innerHTML='<iframe src="'+url+'" width="100%" height="100%" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>'}}}}
function t396_addHtml(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addHtml');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addTooltip(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addTooltip');var fieldsString='width,height,top,left,';fieldsString+='container,axisx,axisy,widthunits,heightunits,leftunits,topunits,tipposition';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element);var tooltip=element.querySelector('.tn-atom__pin');var tooltipContent=element.querySelector('.tn-atom__tip');var tooltipOpenTrigger=element.getAttribute('data-field-tipopen-value');if(window.isMobile||tooltipOpenTrigger==='click'){t396_setUpTooltip_mobile(element,tooltip,tooltipContent)}else{t396_setUpTooltip_desktop(element,tooltip,tooltipContent)}
setTimeout(function(){var atomImages=document.querySelectorAll('.tn-atom__tip-img');Array.prototype.forEach.call(atomImages,function(img){var imgOriginal=img.getAttribute('data-tipimg-original');if(imgOriginal)img.src=imgOriginal})},3000)}
function t396_addForm(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,top,left,';fieldsString+='inputs,container,axisx,axisy,widthunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_addGallery(artBoard,element){element=t396_getEl(element);if(!element)return;tn_console('func: addForm');var fieldsString='width,height,top,left,';fieldsString+='imgs,container,axisx,axisy,widthunits,heightunits,leftunits,topunits';element.setAttribute('data-fields',fieldsString);t396_elem__renderView(element)}
function t396_elem__setFieldValue(element,prop,val,flag_render,flag_updateui,resolution){element=t396_getEl(element);if(!element)return;if(!resolution)resolution=window.tn.curResolution;if(+resolution<1200&&prop!=='zindex'){element.setAttribute('data-field-'+prop+'-res-'+resolution+'-value',val)}else{element.setAttribute('data-field-'+prop+'-value',val)}
if(flag_render==='render')elem__renderViewOneField(element,prop);if(flag_updateui==='updateui')panelSettings__updateUi(element,prop,val)}
function t396_elem__getFieldValue(element,prop){element=t396_getEl(element);if(!element)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=element.getAttribute('data-field-'+prop+'-value')}
if(i>0&&+resolution===breakpoint){dataField=element.getAttribute('data-field-'+prop+'-res-'+breakpoint+'-value');if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=element.getAttribute('data-field-'+prop+'-res-'+slicedBreakpoints[n]+'-value');if(dataField)break}}
if(!dataField)dataField=element.getAttribute('data-field-'+prop+'-value')}});return dataField?dataField:''}
function t396_elem__renderView(element){element=t396_getEl(element);tn_console('func: elem__renderView');var fields=element?element.getAttribute('data-fields'):'';if(!fields)return!1;fields=fields.split(',');fields.forEach(function(field){t396_elem__renderViewOneField(element,field)})}
function t396_elem__renderViewOneField(element,field){element=t396_getEl(element);if(!element)return;var value=t396_elem__getFieldValue(element,field);var elementType;var borderWidth;var borderStyle;var currentValue;var slidesMain;var slidesImg;switch(field){case 'left':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.left=parseFloat(value).toFixed(1)+'px';break;case 'top':value=t396_elem__convertPosition__Local__toAbsolute(element,field,value);element.style.top=parseFloat(value).toFixed(1)+'px';break;case 'width':value=t396_elem__getWidth(element,value);element.style.width=parseFloat(value).toFixed(1)+'px';elementType=element.getAttribute('data-elem-type');switch(elementType){case 'tooltip':var pinSvgIcon=element.querySelectorAll('.tn-atom__pin-icon');Array.prototype.forEach.call(pinSvgIcon,function(pin){var pinSize=parseFloat(value).toFixed(1)+'px';pin.style.width=pinSize;pin.style.height=pinSize});element.style.height=parseInt(value).toFixed(1)+'px';break;case 'gallery':borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.width=currentValue;if(slidesMain)slidesMain.style.width=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.width=currentValue});break}
break;case 'height':elementType=element.getAttribute('data-elem-type');if(elementType==='tooltip')return;value=t396_elem__getHeight(element,value);element.style.height=parseFloat(value).toFixed(1)+'px';if(elementType==='gallery'){borderWidth=t396_elem__getFieldValue(element,'borderwidth');borderStyle=t396_elem__getFieldValue(element,'borderstyle');if(!borderStyle||!borderWidth||borderStyle==='none'){borderWidth=0}
value-=borderWidth*2;currentValue=parseFloat(value).toFixed(1)+'px';slidesMain=element.querySelector('.t-slds__main');slidesImg=element.querySelectorAll('.tn-atom__slds-img');element.style.height=currentValue;if(slidesMain)slidesMain.style.height=currentValue;Array.prototype.forEach.call(slidesImg,function(img){img.style.height=currentValue})}
break;case 'container':t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top');break;case 'inputs':var textArea=element.querySelector('.tn-atom__inputs-textarea');value=textArea?textArea.value:'';try{t_zeroForms__renderForm($(element),value)}catch(err){}
break}
if(field==='width'||field==='height'||field==='fontsize'||field==='fontfamily'||field==='letterspacing'||field==='fontweight'||field==='img'){t396_elem__renderViewOneField(element,'left');t396_elem__renderViewOneField(element,'top')}}
function t396_elem__convertPosition__Local__toAbsolute(element,field,value){element=t396_getEl(element);if(!element)return;var artBoard=element.closest('.t396__artboard');var verticalAlignValue=t396_ab__getFieldValue(artBoard,'valign');var isScaled=t396_ab__getFieldValue(artBoard,'upscale')==='window';var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var isTildaModeEdit=tildaMode==='edit';var isOnlyScalable=t396_isOnlyScalableBrowser();var isScaledElement=!isTildaModeEdit&&isScaled&&isOnlyScalable;var isZoomedElement=!isTildaModeEdit&&isScaled&&!isOnlyScalable;var valueAxisY=t396_elem__getFieldValue(element,'axisy');var valueAxisX=t396_elem__getFieldValue(element,'axisx');var container=t396_elem__getFieldValue(element,'container');value=parseInt(value);var elementContainer;var offsetLeft;var offsetTop;var elementWidth;var elementContainerWidth;var elementHeight;var elementContainerHeight;switch(field){case 'left':elementContainer=container==='grid'?'grid':'window';offsetLeft=container==='grid'?window.tn.grid_offset_left:0;elementContainerWidth=container==='grid'?window.tn.grid_width:window.tn.window_width;var elementLeftUnits=t396_elem__getFieldValue(element,'leftunits');if(elementLeftUnits==='%'){value=t396_roundFloat(elementContainerWidth*value/100)}
if(!isTildaModeEdit&&isScaled){if(container==='grid'&&isOnlyScalable)value=value*window.tn_scale_factor}else{value=offsetLeft+value}
if(valueAxisX==='center'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth/2-elementWidth/2+value}
if(valueAxisX==='right'){elementWidth=t396_elem__getWidth(element);if(isScaledElement&&elementContainer!=='window'){elementContainerWidth*=window.tn_scale_factor;elementWidth*=window.tn_scale_factor}
value=elementContainerWidth-elementWidth+value}
if(isScaledElement&&elementContainer!=='window'){elementWidth=t396_elem__getWidth(element);value=value+(elementWidth*window.tn_scale_factor-elementWidth)/2}
break;case 'top':var artBoardParent=element.parentNode;var proxyMinOffsetTop=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-offset-top'):'0';var proxyMinHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoardParent?artBoardParent.getAttribute('data-artboard-proxy-max-height'):'0';var getElementHeight=function(element){var height=t396_elem__getHeight(element);if(element&&element.getAttribute('data-elem-type')==='image'){var width=t396_elem__getWidth(element);var fileWidth=t396_elem__getFieldValue(element,'filewidth');var fileHeight=t396_elem__getFieldValue(element,'fileheight');if(fileWidth&&fileHeight){var ratio=parseInt(fileWidth)/parseInt(fileHeight);height=width/ratio}}
return height};elementContainer=container==='grid'?'grid':'window';offsetTop=container==='grid'?parseFloat(proxyMinOffsetTop):0;elementContainerHeight=container==='grid'?parseFloat(proxyMinHeight):parseFloat(proxyMaxHeight);var elTopUnits=t396_elem__getFieldValue(element,'topunits');if(elTopUnits==='%'){value=(elementContainerHeight*(value/100))}
if(isScaledElement&&elementContainer!=='window'){value*=window.tn_scale_factor}
if(isZoomedElement&&elementContainer!=='window'){offsetTop=verticalAlignValue==='stretch'?0:(offsetTop/window.tn_scale_factor)}
value=offsetTop+value;var artBoardHeightVH=t396_ab__getFieldValue(artBoardParent,'height_vh');var artBoardMinHeight=t396_ab__getFieldValue(artBoardParent,'height');var artBoardMaxHeight=t396_ab__getHeight(artBoardParent);if(isScaled&&!isTildaModeEdit&&artBoardHeightVH){var scaledMinHeight=parseInt(artBoardMinHeight,10)*window.tn_scale_factor}
if(valueAxisY==='center'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight/2-elementHeight/2+value}
if(valueAxisY==='bottom'){elementHeight=getElementHeight(element);if(isScaledElement&&elementContainer!=='window'){if(verticalAlignValue!=='stretch'){elementContainerHeight=elementContainerHeight*window.tn_scale_factor}else{if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}}
elementHeight*=window.tn_scale_factor}
if(!isTildaModeEdit&&isScaled&&!isOnlyScalable&&elementContainer!=='window'&&verticalAlignValue==='stretch'){if(scaledMinHeight){elementContainerHeight=scaledMinHeight>artBoardMaxHeight?scaledMinHeight:artBoardMaxHeight}else{elementContainerHeight=artBoardParent.clientHeight}
elementContainerHeight=elementContainerHeight/window.tn_scale_factor}
value=elementContainerHeight-elementHeight+value}
if(isScaledElement&&elementContainer!=='window'){elementHeight=getElementHeight(element);value=value+(elementHeight*window.tn_scale_factor-elementHeight)/2}
break}
return value}
function t396_ab__setFieldValue(artBoard,prop,val,resolution){if(!resolution)resolution=window.tn.curResolution;if(resolution<1200){if(artBoard)artBoard.setAttribute('data-artboard-'+prop+'-res-'+resolution,val)}else{if(artBoard)artBoard.setAttribute('data-artboard-'+prop,val)}}
function t396_ab__getFieldValue(artBoard,prop){if(!artBoard)return;var resolution=window.tn.curResolution;var breakpoints=[1200,960,640,480,320];var dataField;breakpoints.forEach(function(breakpoint,i){if(i===0&&+resolution>=breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop)}
if(i>0&&+resolution===breakpoint){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+breakpoint);if(i>1&&!dataField){var slicedBreakpoints=breakpoints.slice(1,i);for(var n=slicedBreakpoints.length-1;n>=0;n--){dataField=artBoard.getAttribute('data-artboard-'+prop+'-res-'+slicedBreakpoints[n]);if(dataField)break}}
if(!dataField)dataField=artBoard.getAttribute('data-artboard-'+prop)}});return dataField?dataField:''}
function t396_ab__renderViewOneField(artBoard,field){t396_ab__getFieldValue(artBoard,field)}
function t396_allelems__renderView(artBoard){if(!artBoard)return!1;tn_console('func: allelems__renderView: abid:'+artBoard.getAttribute('data-artboard-recid'));var ArtBoardelements=artBoard.querySelectorAll('.tn-elem');Array.prototype.forEach.call(ArtBoardelements,function(element){t396_elem__renderView(element)})}
function t396_ab__filterUpdate(artBoard){var filter=artBoard.querySelector('.t396__filter');if(!filter)return;var filterColorRgb=filter.getAttribute('data-filtercolor-rgb');var filterColorRgb2=filter.getAttribute('data-filtercolor2-rgb');var filterOpacity=filter.getAttribute('data-filteropacity');var filterOpacity2=filter.getAttribute('data-filteropacity2');if(filterColorRgb&&!filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb+','+filterOpacity+')'}else if(!filterColorRgb&&filterColorRgb2){filter.style.backgroundColor='rgba('+filterColorRgb2+','+filterOpacity2+')'}else if(filterColorRgb&&filterColorRgb2){filter.style.background='-webkit-gradient(linear, left top, left bottom, from(rgba('+filterColorRgb+','+filterOpacity+')), to(rgba('+filterColorRgb2+','+filterOpacity2+')) )'}else{filter.style.backgroundColor='transparent'}}
function t396_ab__getHeight(artBoard,artBoardHeight){if(!artBoardHeight)artBoardHeight=t396_ab__getFieldValue(artBoard,'height');artBoardHeight=parseFloat(artBoardHeight);var artBoardHeightVH=t396_ab__getFieldValue(artBoard,'height_vh');if(artBoardHeightVH){artBoardHeightVH=parseFloat(artBoardHeightVH);if(!isNaN(artBoardHeightVH)){var artBoardHeightVHpx=window.tn.window_height*artBoardHeightVH/100;if(artBoardHeight<artBoardHeightVHpx){artBoardHeight=artBoardHeightVHpx}}}
return artBoardHeight}
function t396_hex2rgb(hexStr){var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b]}
String.prototype.t396_replaceAll=function(search,replacement){var target=this;return target.replace(new RegExp(search,'g'),replacement)};function t396_elem__getWidth(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'width');value=parseFloat(value);var elWidthUnits=t396_elem__getFieldValue(element,'widthunits');if(elWidthUnits==='%'){var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=window.tn.window_width*value/100}else{value=window.tn.grid_width*value/100}}
return value}
function t396_elem__getHeight(element,value){element=t396_getEl(element);if(!value)value=t396_elem__getFieldValue(element,'height');value=parseFloat(value);var elemType=element.getAttribute('data-elem-type');if(elemType==='shape'||elemType==='video'||elemType==='html'||elemType==='gallery'){var elHeightUnits=t396_elem__getFieldValue(element,'heightunits');if(elHeightUnits==='%'){var artBoard=element.parentNode;var proxyMinHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-min-height'):'0';var proxyMaxHeight=artBoard?artBoard.getAttribute('data-artboard-proxy-max-height'):'0';var artBoardMinHeight=parseFloat(proxyMinHeight);var artBoardMaxHeight=parseFloat(proxyMaxHeight);var elementContainer=t396_elem__getFieldValue(element,'container');if(elementContainer==='window'){value=artBoardMaxHeight*(value/100)}else{value=artBoardMinHeight*(value/100)}}}else if(elemType!=='button'){value=element.clientHeight}
return value}
function t396_roundFloat(n){n=Math.round(n*100)/100;return(n)}
function tn_console(str){if(+(window.tn_comments)===1)console.log(str)}
function t396_setUpTooltip_desktop(element,tooltip,tooltipContent){element=t396_getEl(element);var timer;if(tooltip){tooltip.addEventListener('mouseover',function(){var visibleEls=document.querySelectorAll('.tn-atom__tip_visible');Array.prototype.forEach.call(visibleEls,function(visibleEl){var curTipEl=visibleEl.closest('.t396__elem');var cirTipElID=curTipEl?curTipEl.getAttribute('data-elem-id'):'';if(cirTipElID!==element.getAttribute('data-elem-id')){t396_hideTooltip(curTipEl,visibleEl)}});clearTimeout(timer);if(tooltipContent&&tooltipContent.style.display==='block')return;t396_showTooltip(element,tooltipContent)});tooltip.addEventListener('mouseout',function(){timer=setTimeout(function(){t396_hideTooltip(element,tooltipContent)},300)})}}
function t396_setUpTooltip_mobile(element,tooltip,tooltipContent){element=t396_getEl(element);if(tooltip){tooltip.addEventListener('click',function(){if(tooltipContent&&tooltipContent.style.display==='block'&&tooltip.classList.contains('tn-atom__pin')){t396_hideTooltip(element,tooltipContent)}else{t396_showTooltip(element,tooltipContent)}})}
var elementID=element.getAttribute('data-elem-id');document.addEventListener('click',function(e){if(e.target.closest('.tn-atom__pin')){var zbEl=e.target.closest('.t396__elem');var clickedPinId=zbEl?zbEl.getAttribute('data-elem-id'):'';if(clickedPinId===elementID)return}
t396_hideTooltip(element,tooltipContent)})}
function t396_hideTooltip(element,tooltipContent){if(tooltipContent)tooltipContent.style.display='';if(tooltipContent)tooltipContent.style.left='';if(tooltipContent)tooltipContent.style.transform='';if(tooltipContent)tooltipContent.style.right='';if(tooltipContent)tooltipContent.classList.remove('tn-atom__tip_visible');if(element)element.style.zIndex=''}
function t396_showTooltip(element,tooltipContent){element=t396_getEl(element);var pos=element.getAttribute('data-field-tipposition-value');if(!pos)pos='top';var elSize=element.clientHeight;var elTop=element.getBoundingClientRect().top+window.pageYOffset;var elBottom=elTop+elSize;var elLeft=element.getBoundingClientRect().left+window.pageXOffset;var elRight=elLeft+elSize;var winTop=window.pageYOffset;var winWidth=document.documentElement.clientWidth;var winBottom=winTop+document.documentElement.clientHeight;var tipElHeight=tooltipContent?tooltipContent.offsetHeight:0;var tipElWidth=tooltipContent?tooltipContent.offsetWidth:0;var padding=15;var tipElRight;var tipElLeft;var tipElTop;var tipElBottom;if(pos==='right'||pos==='left'){tipElRight=elRight+padding+tipElWidth;tipElLeft=elLeft-padding-tipElWidth;if((pos==='right'&&tipElRight>winWidth)||(pos==='left'&&tipElLeft<0)){pos='top'}}
if(pos==='top'||pos==='bottom'){tipElRight=elRight+(tipElWidth/2-elSize/2);tipElLeft=elLeft-(tipElWidth/2-elSize/2);if(tipElRight>winWidth){var rightOffset=-(winWidth-elRight-padding);if(tooltipContent)tooltipContent.style.left='auto';if(tooltipContent)tooltipContent.style.transform='none';if(tooltipContent)tooltipContent.style.right=rightOffset+'px'}
if(tipElLeft<0){var leftOffset=-(elLeft-padding);if(tooltipContent)tooltipContent.style.left=leftOffset+'px';if(tooltipContent)tooltipContent.style.transform='none'}}
if(pos==='top'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom>tipElBottom&&winTop>tipElTop){pos='bottom'}}
if(pos==='bottom'){tipElTop=elTop-padding-tipElHeight;tipElBottom=elBottom+padding+tipElHeight;if(winBottom<tipElBottom&&winTop<tipElTop){pos='top'}}
if(tooltipContent)tooltipContent.setAttribute('data-tip-pos',pos);if(tooltipContent)tooltipContent.style.display='block';if(tooltipContent)tooltipContent.classList.add('tn-atom__tip_visible');if(element)element.style.zIndex='1000'}
function t396_hex2rgba(hexStr,opacity){if(!hexStr)return!1;var hex=parseInt(hexStr.substring(1),16);var r=(hex&0xff0000)>>16;var g=(hex&0x00ff00)>>8;var b=hex&0x0000ff;return[r,g,b,parseFloat(opacity)]}
function t396_removeElementFromDOM(el){el=t396_getEl(el);if(el&&el.parentNode){el.parentNode.removeChild(el)}}
function t396_getEl(el){if(el instanceof jQuery){return el.length?el.get(0):null}else{return el}}
if(!Element.prototype.matches){Element.prototype.matches=Element.prototype.matchesSelector||Element.prototype.msMatchesSelector||Element.prototype.mozMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.oMatchesSelector}
if(!Element.prototype.closest){Element.prototype.closest=function(s){var el=this;while(el&&el.nodeType===1){if(Element.prototype.matches.call(el,s)){return el}
el=el.parentElement||el.parentNode}
return null}}